"""add parse columns and document_blocks

Revision ID: 85e3c58e5d9e
Revises: c1e9f4a2b8d7
Create Date: 2026-08-25 15:58:41.003836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e3c58e5d9e'
down_revision: Union[str, Sequence[str], None] = 'c1e9f4a2b8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_blocks',
    sa.Column('version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=50), nullable=False, comment='text / table / title / ...'),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'order_index', name='uq_document_blocks_version_order')
    )
    op.create_index(op.f('ix_document_blocks_public_id'), 'document_blocks', ['public_id'], unique=True)
    op.create_index(op.f('ix_document_blocks_version_id'), 'document_blocks', ['version_id'], unique=False)
    op.add_column('document_versions', sa.Column('parsed_object_key', sa.String(length=512), nullable=True, comment='解析产物(DoclingDocument JSON)对象键'))
    op.add_column('document_versions', sa.Column('parsed_markdown_object_key', sa.String(length=512), nullable=True, comment='解析产物(Markdown)对象键'))
    op.add_column('document_versions', sa.Column('parse_error', sa.String(length=2000), nullable=True, comment='解析失败原因或 partial_success 警告'))
    op.add_column('document_versions', sa.Column('parsing_started_at', sa.DateTime(), nullable=True))
    op.add_column('document_versions', sa.Column('parsed_at', sa.DateTime(), nullable=True))
    op.alter_column('document_versions', 'parse_job_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               comment='docling-serve 任务 id',
               existing_comment='解析任务 id；待 jobs 表创建后补充外键',
               existing_nullable=True,
               postgresql_using="parse_job_id::text")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_versions', 'parse_job_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               comment='解析任务 id；待 jobs 表创建后补充外键',
               existing_comment='docling-serve 任务 id',
               existing_nullable=True,
               postgresql_using="parse_job_id::integer")
    op.drop_column('document_versions', 'parsed_at')
    op.drop_column('document_versions', 'parsing_started_at')
    op.drop_column('document_versions', 'parse_error')
    op.drop_column('document_versions', 'parsed_markdown_object_key')
    op.drop_column('document_versions', 'parsed_object_key')
    op.drop_index(op.f('ix_document_blocks_version_id'), table_name='document_blocks')
    op.drop_index(op.f('ix_document_blocks_public_id'), table_name='document_blocks')
    op.drop_table('document_blocks')
    # ### end Alembic commands ###
